
%YAML: 1.0

dataDir: /home/laijinxiang/docker-0105/dataset/0524-test-18/bdj3-record_data-i # "/home/laijinxiang/edge-slam/bdj3-record_data-i" 
# Car 18
Camera.model: "fisheye"
Camera.intrinstic: [955.3379635, 961.527827, 955.415214, 541.135945] # fx cx fy cy
Camera.distortion: [-0.026463, -0.018112, 0.016949, -0.007098] # k1 k2 k3 k4
Qcg: [0.505820516001542, -0.4988584606367882, 0.5010022618843634, 0.4942495072630623] # qx qy qz qw
Pcg: [0.06400512447560017, 1.695829476938501, -1.788386848651872] # tx ty tz
# Car 15
#Camera.intrinstic: [951.728065, 955.374577, 951.7022555, 556.6750875] # fx cx fy cy
#Camera.distortion: [-0.024871, -0.018594, 0.015173, -0.005791] # k1 k2 k3 k4
#Qcg: [-0.505161241707068, 0.5085381266442339, -0.4884729876203498, -0.4975894231104555] # qx qy qz qw
#Pcg: [0.1016387795887079, 1.725914890100064, -1.766470201637028] # tx ty tz
Camera.imageScale: 0.5
wheelRadius: 0.376

maxDepth: 100.0
minDepth: 3.0

maxDescriptorDist: 3 # or 使用光度残差时重新设置, SSD匹配不准导致该数据集很难有正确的对应
goodDescriptorDistRatio: 0.8 # 使用 ratio * maxDescriptorDist来判断跟踪效果
maxTrackProjectPixelError: 3.0 # 2.0 跟踪成功的条件是重投影dt残差阈值在该范围内

maxDepthConvergeStd: 0.5 # 深度收敛的标准差
abnormalProjectResidual: 8 # 15个像素距离为异常残差值，不能参与优化步骤
huberDelta: 5 # 胡伯核函数参数
keepLastKFnumInWindow: 3 # 滑窗内KF数量控制
maxKFnumInWindow: 8
imgTimeOffset: 0.06 # sec,时间同步误差
needNewKFtrans: 1.0 # 选取新KF的条件
needNewKFMaxMatchEdgeRatio: 0.2 # 匹配边缘点数量小于该阈值时，需要选定新KF
filterPixelError: 1 # 按1个像素误差推导深度三角化不确定度
maxIterationLM: 2 # LM算法迭代次数

messageLevel: 1 # 0-debug, 1-info, 2-error
maxActiveLandmarkEachKF: 250

minGoodTriangulateAngle: 1.5 # deg, 使用深度滤波时不在意视差

fastTh: 20 # 角点，暂不启用，目标是仅利用边缘点
fastNum: 0

relativePoseConstraintWeight: 1 # 先验Hp已经包含了对各pose的约束，所以其实上不需要该约束，除了先验约束值为0的情况

maxKeepEpilorMatchPointNum: 3 # 3 极线约束取最匹配的数量

useInvZ: false
showDebugImg: false
firstImgIdx: 2650
loopClosureImgIdx: 2630

cannyLowerTh: 30
cannyupperTh: 40

# 设定一些极线搜索立体匹配需要的参数，单位均在像素坐标系下
# 存在相邻边缘像素被匹配的情况
minSearchStep: 1 # 与深度有关系，深度大时，视野大，增大该值，深度小时，视野小减小该值，但是由于有边缘特征，所以还是直接按逐个像素点搜索？
minDepthCompareRatio: 0.7
maxDepthCompareRatio: 1.4
pyrLevel: 3

# 暂未启用项
maxGoodTriangulateAngle: 60.0
minTranslation: 0.5 # m, 每隔多少米取1帧图像进行三角化，视差过小时，三角化的距离受噪声影响极大[LSD-SLAM]
nonMaximumSuppressionRatio: 1.0 # 为了减小误匹配，设定最优与次优描述子的比值，暂未启用
descriptorPatchLen: 5
minEpipolarSearchLine: 3
maxEpipolarSearchLine: 60 # most import item for triangulation
best2SecondRatio: 0.9
