dataDir: /home/ht/Opencv_Ceres_Eigen_example/tum_dataset/rgbd_dataset_freiburg1_xyz
# "/home/laijinxiang/edge-slam/bdj3-record_data-i"
# "/home/laijinxiang/docker-0105/dataset/0524-test-18/bdj3-record_data-i"

Camera.model: "pinhole"

## fr1
Camera.intrinstic: [517.3, 318.6, 516.5, 255.3] # fx cx fy cy
Camera.distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633] # d0, d1, d2, d3, d4

# fr2
# Camera.intrinstic: [520.9, 325.1, 521.0, 249.7] # fx cx fy cy
# Camera.distortion: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172] # d0, d1, d2, d3, d4

Qcg: [0, 0, 0, 1] # qx qy qz qw
Pcg: [0, 0, 0] # tx ty tz

Camera.imageScale: 1.0
wheelRadius: 0

maxDepth: 50.0 # 影响重投影匹配，需要设置大点
minDepth: 0.01

matchNoise: 3.0 # 沿极线方向的匹配误差像素

maxDescriptorDist: 10 # or 使用光度残差时重新设置，如果使用去均值的SSD，这个值应该设的小，越大越宽松
useAvgDiff: false
goodDescriptorDistRatio: 0.6 # 使用 ratio * maxDescriptorDist来判断跟踪效果
maxTrackProjectPixelError: 2.0 # 2.0 跟踪成功的条件是重投影dt残差阈值在该范围内

maxDepthConvergeStd: 0.01 # 深度收敛的标准差，由于逆深度与正深度是非线性关系，不能给正深度的收敛标准
abnormalProjectResidual: 15 # 15个像素距离为异常残差值，不能参与优化步骤
huberDelta: 6 # 胡伯核函数参数，sqrt(chi2)
maxProjectError: 12 # 超过这个残差，意味着不能用于优化
keepLastKFnumInWindow: 3 # 滑窗内KF数量控制
maxKFnumInWindow: 7
useMarginalization: false # 是否使用边缘化最老帧
imgTimeOffset: 0.0 # sec,时间同步误差
needNewKFtrans: 0.05 # 选取新KF的条件
needNewKFrot: 180.0 # deg, 纯旋转无法三角化新的图像，故不能作为选择KF条件
maxMeanProjectResidual2CreateKF: 6.0 # 当Track优化pose残差大于该值时，创建新的KF
needNewKFMaxMatchEdgeRatio: 0.1 # 匹配边缘点数量小于该阈值时，需要选定新KF
# TODO: 这个误差模型将极大的影响深度估计，这里直接是将其当作误差角度使用，值为1时不行
filterPixelError: 10 # 按1个像素误差推导深度三角化不确定度

maxIterationLM: 130 # LM算法迭代次数
convergeCostDiffLM: 1e-14
maxLambdaValueLM: 1e12
maxNoImprovementCountLM: 5 # 没有下降的最大次数
iterateLogFreqLM: 30 # 迭代输出频率
initLambda: 100.0 # LM优化算法lambda初值

messageLevel: 1 # 0-debug, 1-info, 2-error
maxActiveLandmarkEachKF: 500

fastTh1: 20 # 角点，暂不启用，目标是仅利用边缘点
fastTh2: 7
fastNum: 0 # 大于周边16个像素多少个
extractFastNumEachFrame: 2000 # 每个帧提取的关键点数量，网格划分依据
maxFlowTrackError: 10 # 光流跟踪最大的误差
optflowWinSize: 21 # 21
optflowLayer: 3

relativePoseConstraintWeight: 1 # 先验Hp已经包含了对各pose的约束，所以其实上不需要该约束，除了先验约束值为0的情况

maxKeepEpilorMatchPointNum: 3 # 3极线约束取最匹配的数量

useInvZ: false
showDebugImg: false
firstImgIdx: 10
loopClosureImgIdx: 10

cannyLowerTh: 80 # 150
cannyupperTh: 120 # 160

# 存在相邻边缘像素被匹配的情况
minSearchStep: 1 # 与深度有关系，深度大时，视野大，增大该值，深度小时，视野小减小该值，但是由于有边缘特征，所以还是直接按逐个像素点搜索？
minDepthCompareRatio: 0.7
maxDepthCompareRatio: 1.4
pyrLevel: 2
# 任何标准差在这范围之外的，都是不正常的
maxObvDepthStd: 10000.0 # 2.0
minObvDepthStd: 0.000000001 # 0.1
minObvTime: 3

minGradientOFkeyPoint: 15
# 当使用梯度之后，该变量不再被需要了?
# 不是的，LSD-SLAM也会选择最大梯度附近[3x3]邻域内的点都作为特征点
maxDTdistOFkeyPoint: 0.1 # DT图像上值不超过该数的选为关键点，用以产生地图点

# 因为是小基线恢复深度，所以该值影响很大，若是设的太大，就应该允许深度使用更多的帧进行初始化，即放大failObv次数
# 若是设的太小，就会产生很多异常点，所以我宁愿设置大点，且不用failObv次数也不愿设置小些
minGoodTriangulateAngle: 0.1 # deg, // 这个角度限制会卡住很多深度估计值

maxGoodTriangulateAngle: 90.0
minTranslation: 0.5 # m, 每隔多少米取1帧图像进行三角化，视差过小时，三角化的距离受噪声影响极大[LSD-SLAM]
nonMaximumSuppressionRatio: 1.0 # 为了减小误匹配，设定最优与次优描述子的比值，暂未启用
descriptorPatchLen: 5
minEpipolarSearchLine: 10
maxEpipolarSearchLine: 30 # most import item for triangulation
best2SecondRatio: 0.7 # 因为存在极线退化场景，为了避免误匹配，越大越宽松
best2SecondDist: 2 # pixels，这个应该可以设置小点，存在边缘检测不稳定情况，越大越宽松
SimErrorRatio: 0.8 # 千分之5
drawGoddEpipolarMatch: true
drawAllEpipolarMatch: false
drawEpipolarMatchStartCol: 300
maxFailObvTimeBeforeCreateDepth: 10

useDepthImage: false # 验证位姿估计算法
depthFactor: 5000 # 深度图的尺度，深度图存储单位为200mm
initWithTrueDepth: false

debugMessageSaveFolder: "./"
debugWithTrueDepthImage: true # 使用真值深度验证估计
# 使用unordered_set存储如下点，只绘制如下点的debug视频，换行不需要加任何额外符号
debugKFpointSet: [97_167]

# 显示相关flag
debugShowGlobalMap: false # 默认显示局部地图
debugRunOnDesktop: false # 是否运行在台式机上，台式机无法显示过多的元素
debugShowOnlineResult3D: true # 是否显示viz3d窗口
